global using EmployeeMangementSystem_Entity.Common.Audited;
global using System.ComponentModel.DataAnnotations.Schema;
global using EmployeeMangementSystem_Entity.Common.CommonProperty;
global using EmployeeMangementSystem_Entity.Common.Status;
global using System.ComponentModel.DataAnnotations;
global using EmployeeMangementSystem_Entity.ViewEntity;