global using Microsoft.EntityFrameworkCore;
global using EmployeeMangementSystem_Entity.UserLogin;
global using EmployeeMangementSystem_Entity.Employee;
global using EmployeeMangementSystem_Entity.Location;
global using EmployeeMangementSystem_Entity.Role;